config/routes.rb
Purchest::Application.routes.draw do
  
  #ROUTES_PROTOCOL = (ENV["RAILS_ENV"] =~ /development/ ? "http" : "http")
  
  resources :discussions
  resources :invitations
  resources :orders
  resources :line_items
  resources :chests
  resources :profiles
  resources :daily_deal_mailings 
  resources :cities
  resources :deals
  resources :merchants
  resources :categories do
    resources :sub_categories
  end

  get "admin_tasks/home"  
  get "home/index"
  get "thorai_orders/index"
    
  match '/subscriptions/new' => 'subscriptions#new', :via => :get
  match '/subscriptions' => 'subscriptions#create', :via => :post
  match "/purchase" => "home#purchase"
  match "/purchase_complete" => "home#purchase_complete"
  

  devise_for :admins
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" } do
    get "/users/show_user_account", :to => "users/registrations#show_user_account" #, :as => 'account'
    get '/users/sign_up/:invitation_token', :to => 'users/registrations#new'
  end

  root :to => "home#index" #, :as => 'home'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    #puts "IP Addressof the computer"
    #puts request.env['REMOTE_ADDR']
    #cookies.delete :_thorai_returning_user
    #puts ENV["RAILS_ENV"]

    #if returning_user?
    @chest = current_chest
    if user_signed_in?
      @user = current_user
      unless (current_user.profile.nil? && current_user.profile.user_interests.empty?)
        #@active_deals = Deal.still_active(DateTime.now).match_user_interests(@user)
        @active_deals = Deal.all
      else
        #@active_deals = Deal.still_active(DateTime.now)
        @active_deals = Deal.all
      end
    else
      #@active_deals = Deal.still_active(DateTime.now)
      @active_deals = Deal.all
    end
    
    if !returning_user?
      cookies.permanent[:_thorai_returning_user] = "t"
      redirect_to subscriptions_new_url
    end
    
  end
  
  def purchase
    @purchase_deal = Deal.find_by_id(params[:deal_id])
    
    if user_signed_in?
      @user = current_user
    else
      session[:_thorai_back_to_c_out] = true
      session[:_thorai_back_url] = request.url
    end
    params[:quantity] = 1;
    @total_price = params[:quantity] * @purchase_deal.deal_price;
  end
  
  def purchase_complete
    
    if user_signed_in?
      @user = current_user
      #AutoConfirmMailer.purchase_confirmation(@user).deliver
      puts "Deal ID"
      puts params[:deal_id]
      save_billing_info = params[:save_billing_info]
      if save_billing_info
        
      end
    else
    end
=begin      
      @user = User.new
      @profile = Profile.new
      @contact_info = ContactInformation.new
      @billing_address = Address.new
      
      @billing_address.street_address = params[:street_address]
      @billing_address.city = params[:city]
      @billing_address.state = params[:state]
      @billing_address.zip_code = params[:zip_code]
      @billing_address = 
      @billing_address.save
      
      @contact_info.address = @billing_address
      @contact_info.email = params[:user_email]
      
      @profile.contact_information = @contact_info

      @user.email = params[:user_email]
      @user.password = params[:password]
      @user.password_confirmation = params[:confirm]
      @user.enabled = true

      @profile.first_name = params[:first_name]
      @profile.last_name = params[:last_name]
      @profile.user_id = @user.id

      @card_holder_name = params[:card_holder_name]
      @card_number = params[:card_number]
      @security_code = params[:security_code]
      @exp_month = params[:exp_month]
      @exp_year = params[:exp_year]
      
      @profile.save
      @user.profile = @profile

      if @user.save
        if user = User.authenticate(@user.user_name, @user.password)
          session[:user_id] = user.id
            # redirect_to session_user_url
        end
          # else
         # render :action => 'new'
      end
    end
=end
  end

end

app/helpers/home_helper.rb
module HomeHelper
  
  def states
    @states = ['AK',
  			      'AL',
        			'AR',
        			'AZ',
        			'CA',
        			'CO',
        			'CT',
        			'DC',
        			'DE',
        			'FL',
        			'GA',
        			'HI',
        			'IA',
        			'ID',
        			'IL',
        			'IN',
        			'KS',
        			'KY',
        			'LA',
        			'MA',
        			'MD',
        			'ME',
        			'MI',
        			'MN',
        			'MO',
        			'MS',
        			'MT',
        			'NC',
        			'ND',
        			'NE',
        			'NH',
        			'NJ',
        			'NM',
        			'NV',
        			'NY',
        			'OH',
        			'OK',
        			'OR',
        			'PA',
        			'RI',
        			'SC',
        			'SD',
        			'TN',
        			'TX',
        			'UT',
        			'VA',
        			'VT',
        			'WA',
        			'WI',
        			'WV',
        			'WY']
    @states
  end
  
end

app/views/home/_active_deal.html.erb
<div class="view-row">
	<div class="dealslist">
		
		<%= form_for LineItem.new(:deal_id => active_deal.id) do |f| %>
		<%= f.hidden_field :deal_id %>
			<h2><%= link_to active_deal.title, deal_path(active_deal) %></h2>
			<div class="deal-img">
				<%= link_to image_tag(active_deal.merchant.picture.url), deal_path(active_deal) %>
			</div>
			<div class="details">
				<div class="discount">
					<label>Discount</label>
					<div class="discount-value"><%= number_to_percentage(active_deal.discount_percent, :precision => 0) %></div>
				</div>
				<div class="button">
					<%= f.submit '' %>
				</div>
				<div class="other-info">
					<div class="other-value">
						<label>Value</label>
						<div class="value"><%= number_to_currency(active_deal.original_price, :precision => 0) %></div>
					</div>
					<div class="other-value">
						<label>Deal Price</label>
						<div class="value"><%= number_to_currency(active_deal.deal_price, :precision => 0) %></div>
					</div>
					<div class="other-value">
						<label>You save</label>
						<div class="value"><%= number_to_currency(active_deal.dollars_saved, :precision => 0) %></div>
					</div>
				</div>
			</div>
		<% end %>		
	</div> <!-- end of deal list -->
</div><!-- end of view row -->

app/views/home/_active_deal.mobile.erb
<div class="arrow">
		
		<% form_for LineItem.new(:deal_id => active_deal.id) do |f| %>
		<%= f.hidden_field :deal_id %>
			<h2><%= link_to active_deal.title, deal_path(active_deal) %></h2>
			<div class="deal-img">
				<%= link_to image_tag(active_deal.merchant.picture.url), deal_path(active_deal) %>
			</div>
			<div class="arrow">
				<div class="arrow">
					<label>Discount</label>
					<div class="discount-value"><%= number_to_percentage(active_deal.discount_percent, :precision => 0) %></div>
				</div>
				<div class="button">
					<%= f.submit '' %>
				</div>
				<div class="other-info">
					<div class="other-value">
						<label>Value</label>
						<div class="value"><%= number_to_currency(active_deal.original_price, :precision => 0) %></div>
					</div>
					<div class="other-value">
						<label>Deal Price</label>
						<div class="value"><%= number_to_currency(active_deal.deal_price, :precision => 0) %></div>
					</div>
					<div class="other-value">
						<label>You save</label>
						<div class="value"><%= number_to_currency(active_deal.dollars_saved, :precision => 0) %></div>
					</div>
				</div>
			</div>
		<% end %>		
</div><!-- end of arrow -->

app/views/home/deal_details.html.erb
<div id="main-content"><!-- main content begins here -->

<div class="top-panel"><!-- top panel starts here -->
	<div class="dealslist">
		<% form_for LineItem.new(:deal_id => @deal.id) do |f| %>
		<%= f.hidden_field :deal_id %>
			<h2><%= @deal.title %></h2>
			<div class="deal-img">
				<%=  image_tag @deal.merchant.picture.url %>
			</div>
			<div class="details">
				<div class="discount">
					<label>Discount</label>
					<div class="discount-value"><%= number_to_percentage(@deal.discount_percent, :precision => 0) %></div>
				</div>
				<div class="button">
					<%= f.submit '' %>
				</div>
				<div class="other-info">
					<div class="other-value">
						<label>Value</label>
						<div class="value"><%= number_to_currency(@deal.original_price, :precision => 0) %></div>
					</div>
					<div class="other-value">
						<label>Deal Price</label>
						<div class="value"><%= number_to_currency(@deal.deal_price, :precision => 0) %></div>
					</div>
					<div class="other-value">
						<label>You save</label>
						<div class="value"><%= number_to_currency(@deal.dollars_saved, :precision => 0) %></div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div><!-- top panel ends here -->

<div class="center-panel">
	<div class="left-pane">
		<div id="block-3">
			<div class="friend"><a href="#">Buy it for a friend</a></div>
			<div class="coupons">39 Coupons bought</div>
			<div class="social-links">
				<div class="title">Share this deal</div>
				<ul>
					<li class="facebook"><a href="#">facebook</a></li>
					<li class="twitter"><a href="#">twitter</a></li>
					<li class="mail"><a href="#">mail</a></li>
				</ul>
			</div>
		</div>

		<div id="block-4">
			<div class="title">Terms and Conditions</div>
			<ul>
			<li>Valid for all items</li>
			<li>Maximum 1 voucher per person</li>
			<li>Taxes will be extra</li>
			<li>Cannot combine with other</li></ul>
		</div>
	</div>

	<div class="content-page">
		<h2 class="title">Description</h2>
		<p><%= @deal.description %></p>
		
		<h3>Discussions on this deal</h3>
		<% if @deal.discussions.empty? %>
				No discussions on this deal yet. Be first to write!
		<% end %>
		<h4 id="discussions_count"><%= pluralize(@deal.discussions.size, "Discussion") %></h4>
		<div id="discussions">
		  <%= render :partial => @deal.discussions %>
		</div>
		
		<% form_for Discussion.new(:deal_id => @deal.id) do |f| %>
		<%= f.hidden_field :deal_id %>
		  <p>
		    <%= f.label :comment, "Comment" %><br />
		    <%= f.text_area :comment, :rows => 5 %>
		  </p>
		  <p><%= f.submit "Add Discussion" %></p>
		<% end %>
		
	</div>
	<div class="clear"></div>
</div>

</div><!-- main content ends here -->

<%= render :partial => "layouts/sidebar" %>
<div class="clear"></div>

app/views/home/index.html.erb
<div id="main-content">
	
	<%= link_to "Refer Friends", new_invitation_path %><br/>
	<%= link_to "Daily deals in your Inbox!", new_daily_deal_mailing_path %>
	<% for active_deal in @active_deals %>
		<%= render :partial => "active_deal", :locals => { :active_deal => active_deal } %>
	<% end %>

</div><!-- main content ends here -->

	<%= render :partial => "layouts/sidebar" %>

<div class="clear"></div>

app/views/home/index.mobile.erb
<% title "Purchest" %>

<ul>
	<% for active_deal in @active_deals %>
		<%= render :partial => "active_deal", :locals => { :active_deal => active_deal } %>
	<% end %>
</ul>

app/views/home/purchase.html.erb
<%= form_tag :controller => "home", :action => "purchase_complete", :method => "post" do %>
	<h3>Your Purchase</h3>
	<table>
	  <tr>
	    <th>Description</th>
	    <th>Quantity</th>
	    <th>Price</th>
	    <th></th>
	    <th>Total</th>
	  </tr>
	   <tr>
	     <td><%= @purchase_deal.title %></td>
	     <td> <%= text_field_tag :quantity, 1 %></td>
	     <td><%= number_to_currency(@purchase_deal.deal_price) %></td>
	     <td>=</td>
			<td><%= number_to_currency(@total_price) %></td>
	   </tr>
	</table>

	<br />

	<strong><h3>Select Payment Method</h3></strong>

	<br />

	<% if !user_signed_in? %>
		<p>
			Already a thorai user? <%= link_to "Sign in", new_user_session_path %>
		</p>
		<strong><p>Personal Information</p></strong>
		<p>
			First Name <br />
			<%= text_field_tag :first_name %>
		</p>
		<p>Last Name<br />
			<%= text_field_tag :last_name %>
		</p>
		<p>Email<br />
			<%= text_field_tag :user_email %>
		</p>
		<p>Password<br />
			<%= password_field_tag :password %>
		</p>
		<p>Confirm<br />
			<%= password_field_tag :confirm %>
		</p>
	<% end %>
	<br />

	<h3>Billing Information</h3>
	<p>
		Cardholder Name<br />
		<%= text_field_tag :card_holder_name %>
	</p>
	<p>Card Number<br />
		<%= text_field_tag :card_number %>
	</p>
	<p>Security Code<br />
		<%= text_field_tag :security_code %>
	</p>
	<p>Expiration Date<br />
		<%= select_month(Date.today, :field_name => :exp_month) %>
		<%= select_year(Date.today, :field_name => :exp_year, :start_year => Date.today.year, :end_year => Date.today.year + 10) %>
		
	</p>
	<p>
		Billing Address<br />
		<%= text_field_tag :street_address %>
	</p>
	<p>City<br />
		<%= text_field_tag :city %>
	</p>
	<p>State<br />
		<%= select_tag :state, options_for_select(states) %>
	</p>
	<p>Zip Code<br />
		<%= text_field_tag :zip_code %>
	</p>
	<p>
		<% if user_signed_in? %>
			<%= check_box_tag 'save_billing_info' %> Save Payment Info
		<% else %>
			<%= check_box_tag 'save_billing_info', 'save_billing_info', false, :disabled => true %> Save Payment Info
		<% end %>
	</p>
	<%= submit_tag "Complete Order" %>
<% end %>

app/views/home/purchase_complete.html.erb
<h1>Purchase Complete</h1>