config/routes.rb
Purchest::Application.routes.draw do
  
  #ROUTES_PROTOCOL = (ENV["RAILS_ENV"] =~ /development/ ? "http" : "http")
  
  resources :discussions
  resources :invitations
  resources :orders
  resources :line_items
  resources :chests
  resources :profiles
  resources :daily_deal_mailings 
  resources :cities
  resources :deals
  resources :merchants
  resources :categories do
    resources :sub_categories
  end

  get "admin_tasks/home"  
  get "home/index"
  get "thorai_orders/index"
    
  match '/subscriptions/new' => 'subscriptions#new', :via => :get
  match '/subscriptions' => 'subscriptions#create', :via => :post
  match "/purchase" => "home#purchase"
  match "/purchase_complete" => "home#purchase_complete"
  

  devise_for :admins
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" } do
    get "/users/show_user_account", :to => "users/registrations#show_user_account" #, :as => 'account'
    get '/users/sign_up/:invitation_token', :to => 'users/registrations#new'
  end

  root :to => "home#index" #, :as => 'home'

end

app/models/chest.rb
class Chest < ActiveRecord::Base

  has_many :line_items, :dependent => :destroy
  
  def add_deal(deal_id)
    current_item = line_items.find_by_deal_id(deal_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:deal_id => deal_id)
      current_item.quantity = 1
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end
  
end

app/controllers/chests_controller.rb
class ChestsController < ApplicationController

  before_filter :authenticate_admin!, :only => :index

  def index
    @chests = Chest.all
  end

  def show
    begin
      @chest = Chest.find(params[:id])  
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid Chest #{params[:id]}"
      redirect_to home_index_path, :notic => 'Invalid Chest'
    end
  end

  def new
    @chest = Chest.new
  end

  def create
    @chest = Chest.new(params[:chest])
    if @chest.save
      flash[:notice] = "Successfully created chest."
      redirect_to @chest
    else
      render :action => 'new'
    end
  end

  def edit
    @chest = Chest.find(params[:id])
  end

  def update
    @chest = Chest.find(params[:id])
    if @chest.update_attributes(params[:chest])
      flash[:notice] = "Successfully updated chest."
      redirect_to @chest
    else
      render :action => 'edit'
    end
  end

  def destroy
    @chest = Chest.find(params[:id])
    @chest.destroy
    session[:chest_id] = nil
    flash[:notice] = "Your chest is currently empty."
    redirect_to home_index_url
  end
end

app/helpers/chests_helper.rb
module ChestsHelper
end

app/views/chests/_chest.html.erb
<% unless chest.line_items.empty? %>
	<div>Your Purchest</div>
	<table>
		<%= render(chest.line_items) %>
	
		<tr>
			<td colspan="2">Total</td>
			<td><%= number_to_currency(chest.total_price) %></td>
		</tr>
	</table>
	
	<%= button_to "Checkout", new_order_url, :method => :get %>
	<%= button_to 'Empty Chest', chest, :method => :delete, :confirm => 'Are you sure?'%>
<% end %>

app/views/chests/_form.html.erb
<%= form_for @chest do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/chests/edit.html.erb
<% title "Edit Chest" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @chest %> |
  <%= link_to "View All", chests_path %>
</p>

app/views/chests/index.html.erb
<% title "Chests" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for chest in @chests %>
    <tr>
      <td><%= link_to "Show", chest %></td>
      <td><%= link_to "Edit", edit_chest_path(chest) %></td>
      <td><%= link_to "Destroy", chest, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Chest", new_chest_path %></p>

app/views/chests/new.html.erb
<% title "New Chest" %>

<%= render 'form' %>

<p><%= link_to "Back to List", chests_path %></p>

app/views/chests/show.html.erb
<% title "Chest" %>

<table>

	<%= render(@chest.line_items) %>	
		
	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(@chest.total_price) %></td>
	</tr>
		
</table>

<%= button_to 'Empty chest', @chest, :method => :delete, :confirm => 'Are you sure?' %>